/* Generated By:JavaCC: Do not edit this line. ClojureParserConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ClojureParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int SINGLE_LINE_COMMENT = 1;
  /** RegularExpression Id. */
  int LPAR = 7;
  /** RegularExpression Id. */
  int RPAR = 8;
  /** RegularExpression Id. */
  int LSQU = 9;
  /** RegularExpression Id. */
  int RSQU = 10;
  /** RegularExpression Id. */
  int LCUR = 11;
  /** RegularExpression Id. */
  int RCUR = 12;
  /** RegularExpression Id. */
  int NUM = 13;
  /** RegularExpression Id. */
  int RATIO = 14;
  /** RegularExpression Id. */
  int DOUBLE = 15;
  /** RegularExpression Id. */
  int INT = 16;
  /** RegularExpression Id. */
  int NIL = 17;
  /** RegularExpression Id. */
  int STR = 18;
  /** RegularExpression Id. */
  int BOOLEAN = 19;
  /** RegularExpression Id. */
  int CHARACTER = 20;
  /** RegularExpression Id. */
  int KEYWORD = 21;
  /** RegularExpression Id. */
  int SYMBOL = 22;
  /** RegularExpression Id. */
  int INTEROP = 23;
  /** RegularExpression Id. */
  int NS = 24;
  /** RegularExpression Id. */
  int NAME = 25;
  /** RegularExpression Id. */
  int LETTER = 26;
  /** RegularExpression Id. */
  int CHAR = 27;
  /** RegularExpression Id. */
  int DIGIT = 28;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<SINGLE_LINE_COMMENT>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\",\"",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
    "\"{\"",
    "\"}\"",
    "<NUM>",
    "<RATIO>",
    "<DOUBLE>",
    "<INT>",
    "\"nil\"",
    "<STR>",
    "<BOOLEAN>",
    "<CHARACTER>",
    "<KEYWORD>",
    "<SYMBOL>",
    "<INTEROP>",
    "<NS>",
    "<NAME>",
    "<LETTER>",
    "<CHAR>",
    "<DIGIT>",
    "\"#\"",
    "\"\\\'\"",
    "\"`\"",
    "\"~\"",
    "\"~@\"",
    "\"@\"",
    "\"#(\"",
    "\"#\\\'\"",
    "\"#_\"",
    "\"^\"",
    "\"#?\"",
  };

}
